[package]
name = "db_tools"
version = "0.1.0"
edition = "2024"

[dependencies]

rocksdb = { git = "https://github.com/rust-rocksdb/rust-rocksdb", branch = "master" }

lazy_static = "1.4.0"

eetf = "0.10.0"

num-bigint = "0.4"
